#服务端口号
server:
  port: 8001
#数据库连接信息
spring:
  application:
    #服务名称
    name: SPRINGCLOUD-PROVIDER-PAYMENT
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.183.138:3306/springcloudH?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

#spring集成Mybatis环境
#entities别名扫描包
mybatis:
  type-aliases-package: com.hewenbin.commons.entities
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    #表示当前服务需要注册如eureka的注册中心
    register-with-eureka: true
    #配置为 true 表示 是否从eurekaserver中抓取已有的服务信息 默认为true 如果是居群 必须配置为true才能使用 ribbon进行负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  #eureka的平台中显示的服务名称 替换其IP+port的显示
  instance:
    instance-id: payment8001
    #访问 路径时显示 IP地址
    prefer-ip-address: true
    #eureka 客户端 向服务端 发送心跳的时间间隔为 2（秒）  （默认为30秒）
    lease-renewal-interval-in-seconds: 2
    #表示 eureka 客户端 向服务端 发送心跳超过5秒 就被删除
    lease-expiration-duration-in-seconds: 5


#eureka:
#  client:
#    register-with-eureka: true #表示是否将自己注册到eureka注册中心
#    fetch-registry: true  # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
#    service-url:
#      defaultZone: http://localhost:7001/eureka  #单机版本的注册方式
